import '@/styles/globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import '@/styles/layout.css';

import type { AppProps } from 'next/app';
import { ThemeProvider } from 'styled-components';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Head from 'next/head';

const theme = {
  colors: {
    primary: '#355C7D',
  }
}

export default function App({ Component, pageProps }: AppProps) {

  return <>
    <ThemeProvider theme={theme}>
      <Head>
        <title>Next.js + TypeScript Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>

      <Header />
      <Component {...pageProps} />
      <Footer />
    </ThemeProvider></>
}
